Rebuilds each member's hours from entries in the signins table.
Skunkworks1983/Timeclock pull request #9
Opened 2023-01-17 00:03 UTC by Ronoman

2023-01-17 00:40 UTC, Ronoman commented
Looks like IntelliJ automatically cleaned up some imports as well as the changes I've implemented.

2023-01-17 07:03 UTC, trdesilva requested changes
generally looks pretty good; mostly just needs the one bugfix and everything else is minor

2023-01-17 07:03 UTC, trdesilva commented on src/io/github/skunkworks1983/timeclock/db/SigninStore.java
> +public class SigninStore {
nit: bracket spacing

2023-01-19 03:27 UTC, Ronoman commented on src/io/github/skunkworks1983/timeclock/db/SigninStore.java
> +public class SigninStore {
I tried so hard... but one slipped through

2023-01-19 04:08 UTC, Ronoman commented
Comments addressed, review round 2 @trdesilva ?

2023-01-19 09:31 UTC, trdesilva commented on src/io/github/skunkworks1983/timeclock/controller/AdminController.java
> +            if(HashUtil.computeHash(ADMIN_PASS_SALT, enteredPass).equals(ADMIN_PASS_HASH) || true)
I'm just gonna go ahead and fix this one

2023-01-19 09:44 UTC, trdesilva approved these changes

2023-01-19 09:44 UTC, merged